#!/bin/bash

sudo rm -r ./models/qo_1h_cp/0/no_costs/train_0
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_1
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_2
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_3
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_4
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_5
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_6
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_7
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_8
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_9
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_10
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_11
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_12
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_13
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_14
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_15
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_16
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_17
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_18
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_19
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_20
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_21
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_22
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_23
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_24
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_25
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_26
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_27
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_28
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_29
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_30
sudo rm -r ./models/qo_1h_cp/0/no_costs/train_31


sudo rm -r ./models/qo_1h_cp/1/no_costs/train_0
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_1
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_2
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_3
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_4
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_5
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_6
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_7
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_8
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_9
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_10
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_11
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_12
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_13
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_14
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_15
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_16
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_17
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_18
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_19
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_20
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_21
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_22
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_23
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_24
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_25
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_26
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_27
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_28
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_29
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_30
sudo rm -r ./models/qo_1h_cp/1/no_costs/train_31

sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_0
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_1
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_2
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_3
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_4
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_5
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_6
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_7
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_8
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_9
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_10
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_11
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_12
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_13
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_14
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_15
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_16
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_17
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_18
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_19
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_20
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_21
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_22
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_23
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_24
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_25
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_26
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_27
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_28
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_29
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_30
sudo rm -r ./models/qo_1h_cp/1_inc/no_costs/train_31

sudo rm -r ./models/qo_1h_cp/2/no_costs/train_0
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_1
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_2
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_3
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_4
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_5
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_6
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_7
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_8
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_9
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_10
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_11
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_12
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_13
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_14
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_15
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_16
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_17
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_18
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_19
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_20
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_21
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_22
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_23
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_24
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_25
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_26
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_27
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_28
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_29
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_30
sudo rm -r ./models/qo_1h_cp/2/no_costs/train_31

sudo rm -r ./models/qo_1h_cp/3/no_costs/train_0
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_1
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_2
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_3
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_4
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_5
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_6
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_7
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_8
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_9
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_10
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_11
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_12
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_13
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_14
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_15
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_16
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_17
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_18
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_19
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_20
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_21
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_22
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_23
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_24
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_25
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_26
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_27
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_28
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_29
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_30
sudo rm -r ./models/qo_1h_cp/3/no_costs/train_31
